version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: 'postgresql://user:password@database:5432/taxiapp'
      GOOGLE_API_KEY: '${GOOGLE_API_KEY}'
      NODE_ENV: 'development'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxiapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  postgres-data:
